name: QuickRTP
version: '1.0-SNAPSHOT'
main: me.idroom1.quickrtp.QuickRTP
version: 1.0
api-version: 1.20
description: A plugin that allows players to randomly teleport in the world using the /rtp command.
author: iDroom
commands:
  rtp:
    description: Randomly teleport in the world.
    usage: /rtp